#!/bin/sh

readonly db_backup_name=db.backup.$(date +"%F:%T").sql

echo "Daily Database Backup"
echo "$WEBDAV_HOSTNAME  $WEBDAV_LOGIN  $WEBDAV_PASSWORD" >&2
mysqldump -P 3306 -h db -u root --password=$CV_DB_ROOT_PASS voiceweb > $db_backup_name
ls -l $db_backup_name
sha1sum $db_backup_name
curl -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD -T $db_backup_name https://nextcloud.nrc-cnrc.gc.ca/remote.php/dav/files/$WEBDAV_LOGIN/
