#!/bin/sh

#TODO: We should only keep X backup of the database.
readonly db_backup_name=db.backup.$(date +"%H%M").sql

echo "15 Minutes Database Backup"
echo "$WEBDAV_HOSTNAME  $WEBDAV_LOGIN  $WEBDAV_PASSWORD" >&2

# Dump the Database to a file.
mysqldump -P 3306 -h db -u root --password=$CV_DB_ROOT_PASS voiceweb > $db_backup_name

# Log size and sha1 of backup.
ls -l $db_backup_name
sha1sum $db_backup_name

# mkdirs
curl -X MKCOL -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/
curl -X MKCOL -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/DBs/
#curl -X PROPFIND -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/ \
#|| curl -X MKCOL -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/
#curl -X PROPFIND -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/DBs/ \
#|| curl -X MKCOL -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/DBs/

# Upload backup.
curl -u $WEBDAV_LOGIN:$WEBDAV_PASSWORD -T $db_backup_name $WEBDAV_HOSTNAME/remote.php/dav/files/$WEBDAV_LOGIN/CommonVoice/DBs/
